[package]
name = "txtr"
version = "0.1.0"
license = "GPL-3.0"
description = "txtr convers images to text."
authors = ["thinkbeard"]
readme = "README.md"
repository = "https://github.com/thinkbeard/txtr.git"
homepage = "https://github.com/thinkbeard/txtr"
categories = ["multimedia::images", "multimedia::encoding"]

[dependencies]
image = "0.18.t "
imageproc = "0.13.0"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
